# model:
#   masking_strategy:
#     class_path: cellm.components.masking.MaskRandomGenes
#     init_args:
#       mask_p: 0.5
#   num_genes: 28231
#   lr: 1e-04
#   weight_decay: 1e-4
#   dropout: 0.0
#   text_emb: False
#   attn: 'nonlinear_attn'
#   n_dim: 1024
#   classify_mode: 'multilabel' #'binary'
#   num_layers: 10
#   label_smoothing: 0
#   logit_adjustment: False
#   batchnorm: False
#   residual: False
#   include_tissue: True
#   uncertainty: False

# data:
#   cell_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_cell_metadata
#   counts_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_counts
#   gene_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_gene_metadata
#   gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
#   val_studies: null
#   # test_studies: null
#   label_column: celltype_id
#   study_column: study
#   sample_column: sample
#   batch_size: 4
#   sample_size: 1500
#   num_workers: 16
#   pad_size: null
#   precompute_val_test_masking: False
#   handle_imbalance: "disease tissue"
#   classify_mode: 'multilabel' #'binary'
#   resample: True

# trainer:
#   devices: 8
#   accelerator: gpu
#   max_epochs: 20
#   check_val_every_n_epoch: 1
#   # log_every_n_steps: 1
#   strategy: 'auto'
#   logger:
#     class_path: lightning.pytorch.loggers.WandbLogger
#     init_args:
#       save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
#       project: disease_class
#       entity: scaliag
#       log_model: all
#       name: null
#   callbacks:
#       class_path: ModelCheckpoint
#       init_args:
#         dirpath: /home/liut61/scratch/disease_class/
#         filename: "disease2classlr1e4_wd1e4_batch32_epoch20_drop0.0_cells1500_multilabel_updatelabel_oversamplediseasetissue_classifytissue_resample_ftcount_nonlinear-attn_new_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4_wd1e4_batch32_epoch10_drop0.0_cells1500_multilabel_updatelabele_oversampler_ftcount_new_nonlinear-attn_{epoch:02d}-{val_accuracy:.2f}" #should has mish#"disease2classlr1e4wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer1layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e3wd1e4batch32epoch40_multilabel_oversample_noresamplingcells_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  #"disease2classlr1e5wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer9layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4wd1e4batch128epoch40_alllabel_oversampling_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  
#         save_weights_only: True
#         save_last: True
#         mode: 'max' 
#         monitor: 'val_accuracy'
#         save_top_k: 4
#       # class_path: EarlyStopping
#       # init_args:
#       #   patience: 5
#       #   mode: 'max' 
#       #   monitor: 'val_accuracy'


# model:
#   masking_strategy:
#     class_path: cellm.components.masking.MaskRandomGenes
#     init_args:
#       mask_p: 0.5
#   num_genes: 28231
#   lr: 1e-04
#   weight_decay: 1e-04
#   dropout: 0.0
#   text_emb: False
#   attn: 'linear_attn'
#   n_dim: 1024 # past 1024
#   classify_mode: 'binary' #'binary'
#   num_layers: 1 # only for transformer
#   label_smoothing: 0
#   logit_adjustment: False
#   batchnorm: False
#   residual: False
#   include_tissue: False
#   uncertainty: False
#   noise_robust: False
#   label_weight: False
#   mask_training: False
#   n_hidden: 512
#   n_hidden_num: 2
#   contras: False
#   contras_ct: False
#   decoupling: False

# data:
#   cell_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_cell_metadata
#   counts_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_counts
#   gene_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_gene_metadata
#   gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
#   val_studies: null
#   # test_studies: null
#   label_column: celltype_id
#   study_column: study
#   sample_column: sample
#   batch_size: 32
#   sample_size: 100
#   num_workers: 16
#   pad_size: null
#   precompute_val_test_masking: False
#   handle_imbalance: False # can be True (only for disease) or "disease tissue" (both disease and tissue)
#   classify_mode: 'binary' #'binary'
#   resample: False
#   tissue_clean: False

# trainer:
#   devices: 1
#   accelerator: gpu
#   max_epochs: 40
#   check_val_every_n_epoch: 1
#   # log_every_n_steps: 1
#   strategy: 'auto'
#   logger:
#     class_path: lightning.pytorch.loggers.WandbLogger
#     init_args:
#       save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
#       project: disease_class
#       entity: scaliag
#       log_model: all
#       name: null
#   callbacks:
#       class_path: ModelCheckpoint
#       init_args:
#         dirpath: /home/liut61/scratch/disease_class/
#         filename: "disease2classlr1e4_wd1e4_batch32_epoch40_drop0.0_cells100_binary_updatelabel_new5121024_linear-attn_testacc_{epoch:02d}-{val_accuracy:.2f}" 
#         save_weights_only: True
#         save_last: True
#         mode: 'max' 
#         monitor: 'val_accuracy'
#         save_top_k: 4
#       # class_path: EarlyStopping
#       # init_args:
#       #   patience: 5
#       #   mode: 'max' 
#       #   monitor: 'val_accuracy'


# model:
#   masking_strategy:
#     class_path: cellm.components.masking.MaskRandomGenes
#     init_args:
#       mask_p: 0.5
#   num_genes: 28231
#   lr: 1e-04
#   weight_decay: 1e-5
#   dropout: 0.0
#   text_emb: False
#   attn: 'linear_attn'
#   n_dim: 1024 # past 1024
#   classify_mode: 'binary' #'multilabel' #'binary'
#   num_layers: 1 # only for transformer
#   label_smoothing: 0
#   logit_adjustment: False
#   batchnorm: False
#   residual: False
#   include_tissue: False
#   uncertainty: False
#   noise_robust: False
#   label_weight: False
#   mask_training: False
#   n_hidden: 512
#   n_hidden_num: 2
#   contras: False
#   contras_ct: False
#   decoupling: False
#   gmlp_seqlen: 100

# data:
#   cell_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_cell_metadata
#   counts_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_counts
#   gene_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_gene_metadata
#   gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
#   val_studies: null
#   # test_studies: null
#   label_column: celltype_id
#   study_column: study
#   sample_column: sample
#   batch_size: 32
#   sample_size: 100
#   num_workers: 4
#   pad_size: null
#   precompute_val_test_masking: False
#   handle_imbalance: False #False
#   classify_mode: 'binary' #'multilabel' #'binary'
#   resample: False
#   tissue_clean: False
#   gene_name: genes
#   simple_mode: False

# trainer:
#   devices: 1
#   accelerator: gpu
#   max_epochs: 10
#   check_val_every_n_epoch: 1
#   # log_every_n_steps: 1
#   strategy: 'auto'
#   logger:
#     class_path: lightning.pytorch.loggers.WandbLogger
#     init_args:
#       save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
#       project: disease_class
#       entity: scaliag
#       log_model: all
#       name: null
#   callbacks:
#       class_path: ModelCheckpoint 
#       init_args:
#         dirpath: /home/liut61/scratch/disease_class/
#         filename: "disease2classlr1e4_wd1e5_batch32_epoch10_drop0.0_cells100_binary_new_linear_attn_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4_wd1e4_batch32_epoch40_drop0.0_cells100_binary_updatelabel_transformer_new_{epoch:02d}-{val_accuracy:.2f}" # "disease2classlr1e4_wd1e4_batch32_epoch4_drop0.0_cells1500_multilabel_updatelabel_diseasetissue_resample_nonlinear_attn_new_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4_wd1e4_batch32_epoch40_drop0.0_cells100_2label_contrasct_resample_linear-attn_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4_wd1e4_batch32_epoch10_drop0.0_cells1500_multilabel_updatelabel_downsampledisease_nonlinear-attn_new_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e5_wd1e4_batch32_epoch10_drop0.0_cells1500_diseasetissue_multilabel_updatelabel_labelweight_transformer1_masktraining_new_{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4_wd1e4_batch32_epoch10_drop0.0_cells1500_multilabel_updatelabele_oversampler_ftcount_new_nonlinear-attn_{epoch:02d}-{val_accuracy:.2f}" #should has mish#"disease2classlr1e4wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer1layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e3wd1e4batch32epoch40_multilabel_oversample_noresamplingcells_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  #"disease2classlr1e5wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer9layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4wd1e4batch128epoch40_alllabel_oversampling_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  
#         save_weights_only: True
#         save_last: True
#         mode: 'max' 
#         monitor: 'val_accuracy'
#         save_top_k: 2
#       # class_path: EarlyStopping
#       # init_args:
#       #   patience: 5
#       #   mode: 'max' 
#       #   monitor: 'val_accuracy'


model:
  masking_strategy:
    class_path: cellm.components.masking.MaskRandomGenes
    init_args:
      mask_p: 0.5
  num_genes: 28231
  lr: 1e-04
  weight_decay: 1e-4
  dropout: 0.0
  text_emb: False
  attn: 'transformer'
  n_dim: 1024 # past 1024
  classify_mode: 'multilabel' #'multilabel' #'binary'
  num_layers: 1 # only for transformer
  label_smoothing: 0
  logit_adjustment: False
  batchnorm: False
  residual: False
  include_tissue: False
  uncertainty: False
  noise_robust: False
  label_weight: False
  mask_training: True
  n_hidden: 512
  n_hidden_num: 2
  contras: False
  contras_ct: False
  decoupling: False
  gmlp_seqlen: 100

data:
  cell_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_cell_metadata
  counts_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_counts
  gene_tdb_uri: /projects/global/gred/resbioai/CeLLM/tiledb/scimilarity_human_10x_gene_metadata
  gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
  val_studies: null
  # test_studies: null
  label_column: celltype_id
  study_column: study
  sample_column: sample
  batch_size: 32
  sample_size: 1000
  num_workers: 16
  pad_size: null
  precompute_val_test_masking: False
  handle_imbalance: "disease tissue" #False
  classify_mode: 'multilabel' #'multilabel' #'binary'
  resample: False
  tissue_clean: False
  gene_name: genes
  simple_mode: True

trainer:
  devices: 1
  accelerator: gpu
  max_epochs: 4
  check_val_every_n_epoch: 1
  # log_every_n_steps: 1
  strategy: 'auto'
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
      project: disease_class
      entity: scaliag
      log_model: all
      name: null
  callbacks:
      class_path: ModelCheckpoint 
      init_args:
        dirpath: /home/liut61/scratch/disease_class/
        filename: "disease2classlr1e4_wd1e-4_batch32_epoch4_drop0.0_cells1000_mutlilabel_diseasetissue_transformermask_{epoch:02d}-{val_accuracy:.2f}"
        save_weights_only: True
        save_last: True
        mode: 'max' 
        monitor: 'val_accuracy'
        save_top_k: 4