# model:
#   masking_strategy:
#     class_path: cellm.components.masking.MaskRandomGenes
#     init_args:
#       mask_p: 0.5
#   num_genes: 28231
#   lr: 1e-04
#   weight_decay: 0.0001
#   dropout: 0.0
#   text_emb: False
#   attn: 'linear_attn'
#   n_dim: 1024
#   classify_mode: 'binary' #'binary'
#   num_layers: 6

# data:
#   cell_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_cell_metadata
#   counts_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_counts
#   gene_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_gene_metadata
#   gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
#   val_studies: null
#   # test_studies: null
#   label_column: celltype_id
#   study_column: study
#   sample_column: sample
#   batch_size: 4
#   sample_size: 100
#   num_workers: 4
#   pad_size: null
#   precompute_val_test_masking: False
#   handle_imbalance: False
#   classify_mode: 'binary' #'binary'

# trainer:
#   devices: 8
#   accelerator: gpu
#   max_epochs: 40
#   check_val_every_n_epoch: 1
#   log_every_n_steps: 1
#   strategy: 'auto'
#   logger:
#     class_path: lightning.pytorch.loggers.WandbLogger
#     init_args:
#       save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
#       project: disease_class
#       entity: scaliag
#       log_model: all
#       name: null
#   callbacks:
#       class_path: ModelCheckpoint
#       init_args:
#         dirpath: /home/liut61/scratch/disease_class/
#         filename: "disease2classlr1e4wd1e4batch128epoch40_2label_nosampling_card8_linearattn-{epoch:02d}-{val_accuracy:.2f}"  
#         save_weights_only: True
#         save_last: True
#         mode: 'max' 
#         monitor: 'val_accuracy'
#         save_top_k: 2
model:
  masking_strategy:
    class_path: cellm.components.masking.MaskRandomGenes
    init_args:
      mask_p: 0.5
  num_genes: 28231
  lr: 1e-04
  weight_decay: 0.0001
  dropout: 0.0
  text_emb: False
  attn: 'mean'
  n_dim: 1024
  classify_mode: 'binary' #'binary'
  num_layers: 1

data:
  cell_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_cell_metadata
  counts_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_counts
  gene_tdb_uri: /gstore/data/omni/scdb/tiledb/scimilarity_human_10x_gene_metadata
  gene_order: /gstore/data/omni/scdb/cleaned_h5ads/gene_order.tsv
  val_studies: null
  # test_studies: null
  label_column: celltype_id
  study_column: study
  sample_column: sample
  batch_size: 4
  sample_size: 100
  num_workers: 4
  pad_size: null
  precompute_val_test_masking: False
  handle_imbalance: False
  classify_mode: 'binary' #'binary'
  resample: False

trainer:
  devices: 8
  accelerator: gpu
  max_epochs: 40
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  strategy: 'auto'
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: /home/liut61/scratch/disease_class/log/ #remember to modify this to your own home path.
      project: disease_class
      entity: scaliag
      log_model: all
      name: null
  callbacks:
      class_path: ModelCheckpoint
      init_args:
        dirpath: /home/liut61/scratch/disease_class/
        filename: "disease2classlr1e4wd1e4batch32epoch40cells100_2label_noresamplingcells_card8_mean-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer1layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e3wd1e4batch32epoch40_multilabel_oversample_noresamplingcells_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  #"disease2classlr1e5wd1e4batch32epoch40cell100_2labeltestnoresampleing_card8_transformer9layer-{epoch:02d}-{val_accuracy:.2f}" #"disease2classlr1e4wd1e4batch128epoch40_alllabel_oversampling_card8_nonlinearattn-{epoch:02d}-{val_accuracy:.2f}"  
        save_weights_only: True
        save_last: True
        mode: 'max' 
        monitor: 'val_accuracy'
        save_top_k: 2